type ColorPaletteTable = {
  mac: {
    darkest: Record<string, string>;
    dark: Record<string, string>;
    light: Record<string, string>;
    lightest?: Record<string, string>;
  };
  win: {
    darkest: Record<string, string>;
    dark: Record<string, string>;
    light: Record<string, string>;
    lightest?: Record<string, string>;
  };
};

export const photoshop: ColorPaletteTable = {
  mac: {
    dark: {
      "--uxp-host-background-color": "#535353",
      "--uxp-host-text-color": "#ffffff",
      "--uxp-host-border-color": "#454545",
      "--uxp-host-link-text-color": "#4b9cf5",
      "--uxp-host-widget-hover-background-color": "#5b5b5b",
      "--uxp-host-widget-hover-text-color": "#ffffff",
      "--uxp-host-widget-hover-border-color": "#5b5b5b",
      "--uxp-host-text-color-secondary": "#e5e5e5",
      "--uxp-host-link-hover-text-color": "#ffffff",
      "--uxp-host-label-text-color": "#ffffff",
    },
    darkest: {
      "--uxp-host-background-color": "#303030",
      "--uxp-host-text-color": "#ffffff",
      "--uxp-host-border-color": "#292929",
      "--uxp-host-link-text-color": "#4b9cf5",
      "--uxp-host-widget-hover-background-color": "#3d3d3d",
      "--uxp-host-widget-hover-text-color": "#ffffff",
      "--uxp-host-widget-hover-border-color": "#3d3d3d",
      "--uxp-host-text-color-secondary": "#9b9b9b",
      "--uxp-host-link-hover-text-color": "#ffffff",
      "--uxp-host-label-text-color": "#ffffff",
    },
    light: {
      "--uxp-host-background-color": "#b8b8b8",
      "--uxp-host-text-color": "#424242",
      "--uxp-host-border-color": "#9c9c9c",
      "--uxp-host-link-text-color": "#4b9cf5",
      "--uxp-host-widget-hover-background-color": "#9d9d9d",
      "--uxp-host-widget-hover-text-color": "#424242",
      "--uxp-host-widget-hover-border-color": "#9d9d9d",
      "--uxp-host-text-color-secondary": "#424242",
      "--uxp-host-link-hover-text-color": "#424242",
      "--uxp-host-label-text-color": "#424242",
    },
    lightest: {
      "--uxp-host-background-color": "#f0f0f0",
      "--uxp-host-text-color": "#4b4b4b",
      "--uxp-host-border-color": "#d1d1d1",
      "--uxp-host-link-text-color": "#4b9cf5",
      "--uxp-host-widget-hover-background-color": "#cecece",
      "--uxp-host-widget-hover-text-color": "#4b4b4b",
      "--uxp-host-widget-hover-border-color": "#cecece",
      "--uxp-host-text-color-secondary": "#606060",
      "--uxp-host-link-hover-text-color": "#4b4b4b",
      "--uxp-host-label-text-color": "#4b4b4b",
    },
  },
  win: {
    dark: {
      "--uxp-host-background-color": "#535353",
      "--uxp-host-text-color": "#ffffff",
      "--uxp-host-border-color": "#454545",
      "--uxp-host-link-text-color": "#4b9cf5",
      "--uxp-host-widget-hover-background-color": "#5b5b5b",
      "--uxp-host-widget-hover-text-color": "#ffffff",
      "--uxp-host-widget-hover-border-color": "#5b5b5b",
      "--uxp-host-text-color-secondary": "#e5e5e5",
      "--uxp-host-link-hover-text-color": "#ffffff",
      "--uxp-host-label-text-color": "#ffffff",
    },
    darkest: {
      "--uxp-host-background-color": "#303030",
      "--uxp-host-text-color": "#ffffff",
      "--uxp-host-border-color": "#292929",
      "--uxp-host-link-text-color": "#4b9cf5",
      "--uxp-host-widget-hover-background-color": "#3d3d3d",
      "--uxp-host-widget-hover-text-color": "#ffffff",
      "--uxp-host-widget-hover-border-color": "#3d3d3d",
      "--uxp-host-text-color-secondary": "#9b9b9b",
      "--uxp-host-link-hover-text-color": "#ffffff",
      "--uxp-host-label-text-color": "#ffffff",
    },
    light: {
      "--uxp-host-background-color": "#b8b8b8",
      "--uxp-host-text-color": "#424242",
      "--uxp-host-border-color": "#9c9c9c",
      "--uxp-host-link-text-color": "#4b9cf5",
      "--uxp-host-widget-hover-background-color": "#9d9d9d",
      "--uxp-host-widget-hover-text-color": "#424242",
      "--uxp-host-widget-hover-border-color": "#9d9d9d",
      "--uxp-host-text-color-secondary": "#424242",
      "--uxp-host-link-hover-text-color": "#424242",
      "--uxp-host-label-text-color": "#424242",
    },
    lightest: {
      "--uxp-host-background-color": "#f0f0f0",
      "--uxp-host-text-color": "#4b4b4b",
      "--uxp-host-border-color": "#d1d1d1",
      "--uxp-host-link-text-color": "#4b9cf5",
      "--uxp-host-widget-hover-background-color": "#cecece",
      "--uxp-host-widget-hover-text-color": "#4b4b4b",
      "--uxp-host-widget-hover-border-color": "#cecece",
      "--uxp-host-text-color-secondary": "#606060",
      "--uxp-host-link-hover-text-color": "#4b4b4b",
      "--uxp-host-label-text-color": "#4b4b4b",
    },
  },
};

export const premiere: ColorPaletteTable = {
  mac: {
    darkest: {
      "--uxp-host-background-color": "#1D1D1D",
      "--uxp-host-text-color": "#D0D0D0",
      "--uxp-host-border-color": "#303030",
      "--uxp-host-link-text-color": "#4096F3",
      "--uxp-host-link-hover-text-color": "#5EAAF7",
      "--uxp-host-label-text-color": "#B0B0B0",
      "--uxp-host-widget-hover-background-color": "#000000",
      "--uxp-host-widget-hover-text-color": "#D0D0D0",
      "--uxp-host-widget-hover-border-color": "#4B4B4B",
      "--uxp-host-text-color-secondary": "#B0B0B0",
    },
    dark: {
      "--uxp-host-background-color": "#323232",
      "--uxp-host-text-color": "#D1D1D1",
      "--uxp-host-border-color": "#3F3F3F",
      "--uxp-host-link-text-color": "#54A3F6",
      "--uxp-host-link-hover-text-color": "#72B7F9",
      "--uxp-host-label-text-color": "#B2B2B2",
      "--uxp-host-widget-hover-background-color": "#1D1D1D",
      "--uxp-host-widget-hover-text-color": "#D1D1D1",
      "--uxp-host-widget-hover-border-color": "#545454",
      "--uxp-host-text-color-secondary": "#B2B2B2",
    },
    light: {
      "--uxp-host-background-color": "#F8F8F8",
      "--uxp-host-text-color": "#464646",
      "--uxp-host-border-color": "#E6E6E6",
      "--uxp-host-link-text-color": "#147AF3",
      "--uxp-host-link-hover-text-color": "#0265DC",
      "--uxp-host-label-text-color": "#6D6D6D",
      "--uxp-host-widget-hover-background-color": "#FFFFFF",
      "--uxp-host-widget-hover-text-color": "#464646",
      "--uxp-host-widget-hover-border-color": "#D5D5D5",
      "--uxp-host-text-color-secondary": "#6D6D6D",
    },
  },
  win: {
    darkest: {
      "--uxp-host-background-color": "#1D1D1D",
      "--uxp-host-text-color": "#D0D0D0",
      "--uxp-host-border-color": "#303030",
      "--uxp-host-link-text-color": "#0098FA",
      "--uxp-host-link-hover-text-color": "#3DACFE",
      "--uxp-host-label-text-color": "#B0B0B0",
      "--uxp-host-widget-hover-background-color": "#000000",
      "--uxp-host-widget-hover-text-color": "#D0D0D0",
      "--uxp-host-widget-hover-border-color": "#4B4B4B",
      "--uxp-host-text-color-secondary": "#B0B0B0",
    },
    dark: {
      "--uxp-host-background-color": "#323232",
      "--uxp-host-text-color": "#D1D1D1",
      "--uxp-host-border-color": "#3F3F3F",
      "--uxp-host-link-text-color": "#2DA5FD",
      "--uxp-host-link-hover-text-color": "#57AFF0",
      "--uxp-host-label-text-color": "#B2B2B2",
      "--uxp-host-widget-hover-background-color": "#1D1D1D",
      "--uxp-host-widget-hover-text-color": "#D1D1D1",
      "--uxp-host-widget-hover-border-color": "#545454",
      "--uxp-host-text-color-secondary": "#B2B2B2",
    },
    light: {
      "--uxp-host-background-color": "#F8F8F8",
      "--uxp-host-text-color": "#464646",
      "--uxp-host-border-color": "#E6E6E6",
      "--uxp-host-link-text-color": "#0067E4",
      "--uxp-host-link-hover-text-color": "#0056BD",
      "--uxp-host-label-text-color": "#6D6D6D",
      "--uxp-host-widget-hover-background-color": "#FFFFFF",
      "--uxp-host-widget-hover-text-color": "#464646",
      "--uxp-host-widget-hover-border-color": "#D5D5D5",
      "--uxp-host-text-color-secondary": "#6D6D6D",
    },
  },
};

//! InDesign "Lightest" theme doesn't currently work, "light" is used instead
//! Waiting on fix from Adobe: https://forums.creativeclouddeveloper.com/t/indesign-theme-bug-on-lightest-mode/11924
// TODO
export const indesign: ColorPaletteTable = {
  mac: {
    darkest: {
      "--uxp-host-background-color": "#323232",
      "--uxp-host-text-color": "#D0D0D0",
      "--uxp-host-border-color": "#303030",
      "--uxp-host-link-text-color": "#4096F3",
      "--uxp-host-link-hover-text-color": "#5EAAF7",
      "--uxp-host-label-text-color": "#B0B0B0",
      "--uxp-host-widget-hover-background-color": "#000000",
      "--uxp-host-widget-hover-text-color": "#D0D0D0",
      "--uxp-host-widget-hover-border-color": "#4B4B4B",
      "--uxp-host-text-color-secondary": "#B0B0B0",
    },
    dark: {
      "--uxp-host-background-color": "#323232",
      "--uxp-host-text-color": "#D1D1D1",
      "--uxp-host-border-color": "#3F3F3F",
      "--uxp-host-link-text-color": "#54A3F6",
      "--uxp-host-link-hover-text-color": "#72B7F9",
      "--uxp-host-label-text-color": "#B2B2B2",
      "--uxp-host-widget-hover-background-color": "#1D1D1D",
      "--uxp-host-widget-hover-text-color": "#D1D1D1",
      "--uxp-host-widget-hover-border-color": "#545454",
      "--uxp-host-text-color-secondary": "#B2B2B2",
    },
    light: {
      "--uxp-host-background-color": "#F8F8F8",
      "--uxp-host-text-color": "#464646",
      "--uxp-host-border-color": "#E6E6E6",
      "--uxp-host-link-text-color": "#147AF3",
      "--uxp-host-link-hover-text-color": "#0265DC",
      "--uxp-host-label-text-color": "#6D6D6D",
      "--uxp-host-widget-hover-background-color": "#FFFFFF",
      "--uxp-host-widget-hover-text-color": "#464646",
      "--uxp-host-widget-hover-border-color": "#D5D5D5",
      "--uxp-host-text-color-secondary": "#6D6D6D",
    },
  },
  win: {
    darkest: {
      "--uxp-host-background-color": "#323232",
      "--uxp-host-text-color": "#E1E1E1",
      "--uxp-host-border-color": "#454545",
      "--uxp-host-link-text-color": "#0098FA",
      "--uxp-host-link-hover-text-color": "#3DACFE",
      "--uxp-host-label-text-color": "#B0B0B0",
      "--uxp-host-widget-hover-background-color": "#000000",
      "--uxp-host-widget-hover-text-color": "#D0D0D0",
      "--uxp-host-widget-hover-border-color": "#4B4B4B",
      "--uxp-host-text-color-secondary": "#B0B0B0",
    },
    dark: {
      "--uxp-host-background-color": "#535353",
      "--uxp-host-text-color": "#E1E1E1",
      "--uxp-host-border-color": "#454545",
      "--uxp-host-link-text-color": "#2DA5FD",
      "--uxp-host-link-hover-text-color": "#57AFF0",
      "--uxp-host-label-text-color": "#B2B2B2",
      "--uxp-host-widget-hover-background-color": "#1D1D1D",
      "--uxp-host-widget-hover-text-color": "#D1D1D1",
      "--uxp-host-widget-hover-border-color": "#545454",
      "--uxp-host-text-color-secondary": "#B2B2B2",
    },
    light: {
      "--uxp-host-background-color": "#B8B8B8",
      "--uxp-host-text-color": "#313131",
      "--uxp-host-border-color": "#E6E6E6",
      "--uxp-host-link-text-color": "#0067E4",
      "--uxp-host-link-hover-text-color": "#0056BD",
      "--uxp-host-label-text-color": "#6D6D6D",
      "--uxp-host-widget-hover-background-color": "#FFFFFF",
      "--uxp-host-widget-hover-text-color": "#464646",
      "--uxp-host-widget-hover-border-color": "#D5D5D5",
      "--uxp-host-text-color-secondary": "#6D6D6D",
    },
    lightest: {
      "--uxp-host-background-color": "#F0F0F0",
      "--uxp-host-text-color": "#313131",
      "--uxp-host-border-color": "#E6E6E6",
      "--uxp-host-link-text-color": "#0067E4",
      "--uxp-host-link-hover-text-color": "#0056BD",
      "--uxp-host-label-text-color": "#6D6D6D",
      "--uxp-host-widget-hover-background-color": "#FFFFFF",
      "--uxp-host-widget-hover-text-color": "#464646",
      "--uxp-host-widget-hover-border-color": "#D5D5D5",
      "--uxp-host-text-color-secondary": "#6D6D6D",
    },
  },
};
